pub struct Config {
    pub config_file: &'static str,
    pub build_dir: &'static str,
    pub data_dir: &'static str,
    pub debug_dir: &'static str,
    pub release_dir: &'static str,
    pub library_dir: &'static str,
    pub static_dir: &'static str,
    pub dynamic_dir: &'static str,
    pub object_dir: &'static str,
    pub binary_dir: &'static str,
    pub include_file: &'static str,
    pub lib_file: &'static str,
    pub object_data: &'static str,
    pub version: &'static str,
    pub dependencies: &'static str,
    pub module_dir: &'static str,
    pub log: &'static str,
}

pub const CONFIG: Config = Config {
    config_file: "config.toml",
    build_dir: "crb",
    data_dir: "data",
    debug_dir: "debug",
    release_dir: "release",
    library_dir: "library",
    static_dir: "static",
    dynamic_dir: "dynamic",
    object_dir: "obj",
    binary_dir: "bin",
    include_file: "Include.include.crb", 
    lib_file: "Lib.lib.crb", 
    object_data: "object_data.o.crb",
    version: "v0.0.1",
    dependencies: "dependencies.d.crb",
    module_dir: "module",
    log: "crab.log",
};

