[package]
name = "crab"
version = "0.0.1"
edition = "2024"

[dependencies]
chrono = "0.4.41"
clap = {version = "4.5.45", features = ["derive"]}
rayon = "1.11.0"
regex = "1.11.1"
serde = {version = "1.0.219", features = ["derive"]}
toml = "0.9.5"
